version: '3.8'

services:
  api:
    build: .
    container_name: report-summarizer-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ${GOOGLE_SERVICE_ACCOUNT_PATH}:/app/service-account.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_SERVICE_ACCOUNT_PATH=/app/service-account.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scheduler:
    build: .
    container_name: report-summarizer-scheduler
    command: python scripts/scheduler.py
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ${GOOGLE_SERVICE_ACCOUNT_PATH}:/app/service-account.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_SERVICE_ACCOUNT_PATH=/app/service-account.json
    restart: unless-stopped
    depends_on:
      - api

volumes:
  reports:
  logs: